spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: http://movie-service
          predicates:
            - Path=/movies/**
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/users/**
        - id: watch-history-service
          uri: http://watch-history-service
          predicates:
            - Path=/watched/**
        - id: recommendation-service
          uri: http://recommendation-service
          predicates:
            - Path=/recommendations/**
  config:
    import: "optional:configserver:"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
