spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexttowatch
    username: postgres
    password: your-password-here
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
